export enum CliExitCode {
  ALREADY_RUNNING = 1,
  NO_SERVER = 2,
  SESSION_CONFLICT = 3,
  NO_DETATCHED_SESSION = 4,
  SESSION_NOT_FOUND = 5,
  SESSION_ALREADY_CONNECTED = 6,
  MULTIPLE_CANDIDATE_SESSIONS = 7,
  UNKNOWN_ERROR = 255,
}

export default { CliExitCode };
